
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szrbcghnsfbmqxhuxkyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6cmJjZ2huc2ZibXF4aHV4a3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjk4NjIsImV4cCI6MjA1ODg0NTg2Mn0.ZcsbZOmc4j0ghjy-AV-9tUW57gsVMM56bMaQgns7aD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
    // Disable email verification during development
    flowType: 'pkce'
  }
});
