
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epdikyzqkywtwzsoplio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZGlreXpxa3l3dHd6c29wbGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTY5NTEsImV4cCI6MjA1OTA3Mjk1MX0.S-iR8MSB3W46oC_B5arqovGg1dPVecp8P6Prpsy6kec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase-auth',
  },
});
