// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsxambdastjnhtunnaxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeGFtYmRhc3Rqbmh0dW5uYXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzY5NTMsImV4cCI6MjA1ODc1Mjk1M30.b8l0fMu60R1H6Zqst3ifuplFRZZVX96twQhcaDaaU9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);